### ISSUE TITLE
[RFE] Export Apps list as CSV

### ISSUE THREAD

**Issue by npmaslow** [f5devcentral/vscode-f5-flipper#15]
**Is your feature request related to a problem? Please describe.**
When planning for tenant organization with the customer, it would be useful to have a CSV list of all the names/addresses for the customer to annotate. 

**Describe the solution you'd like**
Allow display of the list of Apps (name, virtual server type, IP) as a CSV in a text pane.

**Describe alternatives you've considered**
Using optical character recognition in a MacOS screen capture works but is multi-step and clunky.

**Additional context**
This is a request by professional services to use the script in migration situations.

**Comment by DumpySquare** [comment]
example:

name,vs-type,vs-subType,ip,port

groot-cs-vsvr,cs,SSL,192.168.10.65,443

![image](https://github.com/f5devcentral/vscode-f5-flipper/assets/3260966/be0fb1a3-8c0f-4c74-bb45-a30d520b4005)



![image](https://github.com/f5devcentral/vscode-f5-flipper/assets/3260966/2a374a1e-d142-4c3e-8bd1-fe43a2fcee22)

**Comment by DumpySquare** [comment]
complete in pending release v1.1
