### ISSUE TITLE
[RFE] Group or sort Apps category by virtual IP address

### ISSUE THREAD

**Issue by npmaslow** [f5devcentral/vscode-f5-flipper#17]
**Is your feature request related to a problem? Please describe.**
The Apps list does not automatically sort by IP address ascending or descending, so it is not always clear how many ports and virtual servers are being configured for a specific virtual IP. If we make use of the AS3 "Application" class the 80/443/whatever port of an application can be grouped together in one AS3 Application class to allow more commonality in profile and pool definitions - this would be made easier if virtual servers of the same IP address were listed together or in order.

**Describe the solution you'd like**
Either sort the Apps output by ascending or descending IP address, or allow each App category to be port independent to group all ports of an application together.

**Describe alternatives you've considered**
Currently I end up re-declaring an application if I have to add more virtual servers to it, which is more complex.

**Additional context**
N/A

**Comment by DumpySquare** [comment]
apps list is now sorted by IP descending to put all the 0.0.0.0 (and no matches) at the bottom - pending v1.1 release
