### ISSUE TITLE
[BUG] Flipper 1.6.0 Service Parsing Error

### ISSUE THREAD

**Issue by npmaslow** [f5devcentral/vscode-f5-flipper#29]
**Describe the bug**
In the 1.6.0 build, when an ns.conf is loaded the 'bind lb verver service1' shows the correct service name, but that doesn't match up to the 'add service1' listed below it where the port is extracted from, and the 'add server' where the IP is extracted from. This issue is not present in the 1.5.0 build.

**To Reproduce**
F5 PS encountered this in a migration project and will provide data internally.

**Expected behavior**
The add and bind parsings for the 'service' information should match.

**Screenshots**
Data will be provided internally.

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version Flipper 1.6.0

**Comment by DumpySquare** [comment]
this is fixed in the pending v1.7.0 release
