### ISSUE TITLE
[RFE] Processing vservers using IPv6 addresses 

### ISSUE THREAD

**Issue by markjackman** [f5devcentral/vscode-f5-flipper#43]
**Describe the bug**
vserver with IPv6 address results in the below errors and conf file processing is stopped:

1 [2024-10-10T17:26:37.266Z] [ERROR]: regex "/(?<name>("[\S ]+"|[\S]+)) (?<protocol>\S+) (?<ipAddress>[\d.]+) (?<port>(\d+|\*)) (?<opts>[\S ]+)/" - failed for line "add lb vserver IPv6-vserver HTTP 1234:567:890:1:aaaa:bbbb:cccc:32 80 -persistenceType NONE -cltTimeout 180"
1 [2024-10-10T17:26:37.267Z] [ERROR]: [TypeError: lbApps is not iterable (cannot read property undefined)

Once IPv6 address is replaced with IPv4 address the conf file is processed properly

**To Reproduce**
Import netscaler conf file with vserver configured with IPv6 address

**Expected behavior**
The conf file should be processed without errors

**Comment by DumpySquare** [comment]
pending enhancement in v1.11.0 in the "3 APPLE_443_HTTPS" app
